CREATE TABLE applicant
(
    pk                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id                  UUID                                    NOT NULL,
    first_name          VARCHAR(255)                            NOT NULL,
    last_name           VARCHAR(255)                            NOT NULL,
    monthly_income      DECIMAL,
    request_loan_amount DECIMAL,
    monthly_payment     DECIMAL,
    status              VARCHAR(255),
    credit_check        BOOLEAN,
    balance             DECIMAL,
    loan_pk             BIGINT,
    email               VARCHAR(255)                            NOT NULL,
    approved_by         VARCHAR(255),
    tenor               INTEGER                                 NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE,
    updated_at          TIMESTAMP WITHOUT TIME ZONE,
    version             INTEGER                                 NOT NULL,
    CONSTRAINT pk_applicant PRIMARY KEY (pk)
);

CREATE TABLE loan
(
    pk         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id         UUID                                    NOT NULL,
    credited   DECIMAL,
    due_date   TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    version    INTEGER                                 NOT NULL,
    CONSTRAINT pk_loan PRIMARY KEY (pk)
);

ALTER TABLE applicant
    ADD CONSTRAINT uc_applicant_email UNIQUE (email);

ALTER TABLE applicant
    ADD CONSTRAINT FK_APPLICANT_ON_LOAN_PK FOREIGN KEY (loan_pk) REFERENCES loan (pk);

DROP SEQUENCE applicant_pk_seq CASCADE;