CREATE TABLE loan
(
    pk         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id         UUID                                    NOT NULL,
    credited   DECIMAL,
    due_date   TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    version    INTEGER                                 NOT NULL,
    CONSTRAINT pk_loan PRIMARY KEY (pk)
);